#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 32aed7c1-e418-481f-9525-d997a49c9593
# Source File: Server Build Tool.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
CgIAAB+LCAAAAAAABACNkV1rwyAUhu8L/Q/ifWptE1rBeLF2HbvYB23Y7XDJyXCYGDQZ67+fmUlJ
GYxdPvqe98EjP0JuPsGe97KVYj5DiD9b8wF5+wMeX8A6ZWpBF5STEYa7g9JwvxfrlYRik9MIYrqN
4i0tI5askqhgbCNjlrOErTkZwsPoYMnODYglJ1Mcy40uvA6Rqc0NMCA6QgkW6hweZQUpxuimU7pI
8RKLUytt2zWLxrkg/3t0J7WOHqSqD8ZWr40rp13juS8r/112p82b1L6KTqrQzlSVrIvbrxbqfpcp
zmwHWIS08wZ6ZQgQ3n3ZU6Anq95VLXUf6L3iBNb/ZZChzBjt2xo/wcmv6HzGydXffwN5llF/CgIA
AA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.122
     Generated on:       7/5/2016 4:21 PM
     Generated by:       Phillip Marshall
     Organization:       White & Case
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
YgMAAB+LCAAAAAAABAC9k01LA0EMhu9C/8PQ87If3a5rYXZBWnopqFhRr9lttgzOR0lmLPvvbatU
0YMgsuSSNyF5CEnkPbbuFalfgAdxcFg5W40n43p0IYS8JbVVFvRSabwBg/XaA/mwi3fMMvmRPdVc
M6NptEI+6c9IXxtuHWnVROLxgzSN06NFYh60D4SVxeAJdCTuwqFHu8L+wb2grZqyhKItLrNZPsX0
aiaTc9fvlHXPHs0QjPhJ2Y3bc7x0ZHgQ4nFPw4AI9spu/8JK867oyi7LNkUKOfzOejZ6kJnmjvD/
QWf5fvIy+fpT9RvJGdnIYgMAAA==#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Call-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}






#endregion Source: Startup.pss

#region Source: MainForm.psf
function Call-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
zswAAB+LCAAAAAAABADtXW1z2joW/r4z+x80fMnuDJvgFyCZSZhJSNqbe0ObDSm3u18yAkTirbEZ
26Th/vqVzEsxyCD5RYqIpp22KRLnSOf4POc8PpbPH9DAf0XB7BpGEOB/hI7vXVTMSuvvfwPg/Gvg
PDsedD85LvoCx6jVgY73yQ/Gx5NwdH6y9fF8Uv9/aBCBaDZBF5XuLIzQ+PhPxxv6P8NjMnf+ZxXQ
PqqC3kIH+7hGflVBe+pG0wBdeGgaBdCtgvtp33UGf6DZo/8DeRf9ZhPWB/WGcWbZqHZ6VgEeVuWi
Qr6vAgYvjjsM8LBK2/eiwHfD+dKwnveBP0FBNFuMv4KDH23f9YNK63IQOa+oDScR1uT8ZDkwZWLb
dZAXdZ2/UKVlmI3TKji1rb2zyH5VWkTJvUO7EQyiez90iDqVVhtLQ0F3ECC0X7lH9BZVYrMBuqyb
V/x1i8F3PhzOdXoi/zw/iT9cjtxv1wdn8EIEXvlvpZs3wLIiLKvvvxm7zLy9JXf+AM53sl4FjXpz
a0/SjLUukmHS0iPqRhUYTZthxiPs33pD9FZpNUyW4bFtV59umfZkbjF2+30O/OlEhPGeiSCyjbWs
prPqWHyd2XS/BDIbzrKtKjDrLBPW7MbiGHh4N/In+EqDbohoE/ab6st0jLA/fptc+z+90u1184aH
XwckKPpTEn12m22X4eIAaTRo27o9rQPfnPF0jK9UpuFzW28pyzT3AcHhV8+dVVqPwZRmlDQ/IZe3
uR3vd/uJmbL+9Wjcg+4UtV+g94yGlFU9rX+eDNVb1z6TS4mK3PEibr2RvxDI60trQL0Yfuc8v0RM
FkjEfmYvxAt1XMdDHL4xd8XNpZbriWa9iXMPGnLsckXjjG1CDDaPLwgctY+q4Oga/wG9ITi6PwJD
sswQwAABOI38Md7iAXTdGcA5CozQ8BjcuwiGCBva9/FfL/5PMIbeDCDi1MvpM38KPISGYOQHIHpx
QtDrHNOiYwbfbvvjvi/CuR8uO0tZvH59jX8k0bwbzdzYd+Y/3jkhm2/feLDvklCRBivbU8jqYRQ5
3vNqMrPP3eJtTKwHDyH/lzRDNwrwt1fBOBz4gev0i9jqFnZxIkmKbFui7FOJso2GROGWTIs3ZJrc
MGUa3axvWz0DztZoxU8aZq5FUA7ss4w6ydZ5se+0IHy5g33kigCXLnKxKvjbYonZ03C8W0223erA
4NkhFVcVLH7zGTOpMbdJ2VK0NZPS6vm0dGaRlsxVxDkHAkMUOgHOQeCYZNnAHwG8BPCPz1f/VC0T
6bXvv4U6F9G5iM5Fys5F+CHRZotS8yCauJLLx8SGUpgYb06BqGiy1c+5UJGic/m4yOgHKbh4vcDF
L9NxHwUEF9t+gML9rqIAC32WlYQmFDR1X3eT0DTCJcXUFhZxyklBMw7PTUGL4gt7HfL3rTeZZmEL
M2QiOSJ1QlUe6u7MysAiGykT1llkYqUViZzU72ntsyIIZEEBP7EGRQL+ts68zmFxB3xGIng94N+Q
GwuJeN/rALKEg4jzpznivE3d/91xnkouFBbn6ywwUkScF1axtqdh5I+dv+JdX6VHg49RwmYHnd3b
xg1C3PUC7Zb3BgjNtULDeMoKjXYr/kSbpA5M0RenBlzt0L182GKckFKnJFQ/CNRq5kAty+avTlj6
oXKgFgsoKoVaj2g8cWGEVtfJB+FcswNW6o6VjlUprQ77oSpVZcVRamtdagAUXe3SsYkWu9ihaan0
QaBSIwcqmUwUVRKVqKR0cajEAnpKoRLp58faBqjt4owIBRqU9oSUtA0rHZNSlNyPSWkaKw5Jm8tS
DJp2q186JUyLkxx3ebDyIVEe+AFYLOAg4KqeA64MaqPMbrhimZEDrljQUCm4uul+X7jbR2lZyY5U
lL3iCitZmgJSxu8HKYqyiuMTXtFvfhip1nNAV5vbcXhLJrbOzzQ8wkoDovWhwZGdA47O+IsnlmcP
c6ARC9gphUZkv92vo5Ez0Kwec4DZtWml4xNDIwQdn3ZprThQ0ZamBlalal46XGXomViDq1hvMFec
QBYppwYo5RFU9VDLzNMnxw1aLE/A5wAtmj8qDVq9+bkQsnBK0fb9y47xr8XOSewpv7x/D1rc7NiL
0lvcE85ber6QuWdlQ1HFU4TFalYg++4zg02FS08I8nWjLNQFD+j5UNpRMh+2E5/YYjIdkJJMBNjP
2rHOSM+LxXfUTp3pqB2F+uV/nRRSfyL7kvGYjVyN8w1yrVGZilR+iq41xwVu1GoZbpjQ2Yt3fHzK
r42y5ZqXsX1i07y2WPNSg4ES5rWkmtdoZjOvJda81DJOCfOacs3L2Ge7aV5TrHmp2KyEeQ2p5qUe
W7ffuoZY61Izu/d8psJ6kvKr0eOj3Rkwmkae7G5r43gc7ew0y91rKjeoiqO5KPo4DXwyqUCJ1NuV
TNpPouxPEmV/lij7N4mybyXK/l2i7D8kyr6TKLsjUfYXibK/SpT9b4myHyTK7kqU/ShR9jeJsnsS
Zf8pUfZ3ibL/I1H2f/PenG3kqd6S1QhH6WYbGSo3W63DyBI3MQrquWqkPTBX8K3VdN15jczLA1Ef
Uk+7yRprqKxTrB6wyekUcwpGtFsktS+dH7R5TqZf6aYu1WNrqkdTPZrq0VSPpno01aOpHk31aKpH
Uz2a6tFUTz6qJ3OfnmCqp6ib9KKrertQqqcmtKbf1L1sqsfiKumVpnrILuX1h7oM7m+pd/n8Ds95
akSQku/hWb/YPnrPWGYoEt8zZhfVOC7B0SxNJGoiUROJmkjURKImEjWRqIlETSRqIlETiZpIzEUk
Zn8iVCyRSH/+XwHOyCqSSDSofGppvNGm7qUTiYwTCicSJZTzpi7ndTmvy3ldzutyXpfzupzX5bwu
53U5r8t5Xc7nK+cznwAktpw3qW+MVKCcN4ss56nHG5dWzW+qXnY1b7KdFXsQ1byhq3ldzetqXlfz
uprX1byu5nU1r6t5Xc3ral5X87mq+cwHvgou5os60Fd0MW8UVsyzv4WioGJ+U/XSi/mUl6scYjFv
ffRHOrI3BYl/pMNSlUm0Cz43SPQzhqLPDeLqDVL/3CDzwwehzLcyJAShojIgKdT1B3e0zFm2eD8z
VT050SjsyWnRWbawB6dNnreqF/3gtHh/KDj5EesVgnMf1jhRSu4j4Q57MaFC+N11YaGC8Yn7wwgV
VlH+IP7hCXEOQcsLDtUh7OJyCdHH8og7hYXnnfeqO4RZbDIhGjcEJxMWF5OreDJhFesawiFEtG9w
teyx+wb/K7CvplHke6V7CvaBkfOMZ/Y6c4l8L8K+dqDrPz+gEIuvtNrQG1CNxM13pLth/MLtRo39
hdtbK2SYuXShtHdOpjsQ/e2PVPdZKQZ6HYZJ30LUc8IpdGOS6QoOfrR91w9SaZ/zm1fkRUszY1/4
QdmLp/iD85N47Lv31QDBKKOj5vC4Oqe/JbRkdrZTfl8zmF4JP/e1WCmBjpbYhL1elvzhMgzRGHsE
CpdjF/8zaxXYoXB+svrWTSlzPxYho/BrZb9EglpiBAXwZ9xWwi+rZo3qo+bIMIb1GrTgflnfx66Q
NbUx2hcvaPXj3OXPTx7QwH9FwYzYqvV/ozsejc7MAAA=#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$Form = New-Object 'System.Windows.Forms.Form'
	$richtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$groupbox10 = New-Object 'System.Windows.Forms.GroupBox'
	$ExtraDriveCounter = New-Object 'System.Windows.Forms.NumericUpDown'
	$DriveInfoTextBox = New-Object 'System.Windows.Forms.TextBox'
	$RAMComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$RAMSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$VCPUsComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$VCPUsSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox9 = New-Object 'System.Windows.Forms.GroupBox'
	$VMnameInputBox = New-Object 'System.Windows.Forms.TextBox'
	$VMnameInputBoxLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox8 = New-Object 'System.Windows.Forms.GroupBox'
	$CustomizationSelectioncomboBox = New-Object 'System.Windows.Forms.ComboBox'
	$CustomizationSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox7 = New-Object 'System.Windows.Forms.GroupBox'
	$TemplateSelectionComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$TemplateSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox6 = New-Object 'System.Windows.Forms.GroupBox'
	$DataStoreClusterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$DataStoreClusterSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox5 = New-Object 'System.Windows.Forms.GroupBox'
	$ESXClustersComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ESXHostsSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox4 = New-Object 'System.Windows.Forms.GroupBox'
	$LocalOfficeSelectionComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$LocalOfficeSelectionLabel = New-Object 'System.Windows.Forms.Label'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$VCenterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$VCenterSelection = New-Object 'System.Windows.Forms.Label'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$ExtraDrive5_SizeTextBox = New-Object 'System.Windows.Forms.TextBox'
	$ExtraDrive4_SizeTextBox = New-Object 'System.Windows.Forms.TextBox'
	$ExtraDrive3_SizeTextBox = New-Object 'System.Windows.Forms.TextBox'
	$ExtraDrive2_SizeTextBox = New-Object 'System.Windows.Forms.TextBox'
	$ExtraDrive1_SizeTextBox = New-Object 'System.Windows.Forms.TextBox'
	$ExtraDrive5_DataStoreComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive5_letterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive5_SelectionLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive5_DatastoreLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive4_letterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive4_SelectionLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive5_SizeLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive4_DataStoreComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive3_letterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive3_SelectionLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive2_letterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive2_SelectionLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive1_letterComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive1_SelectionLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive3_DataStoreComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive4_DatastoreLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive2_DataStoreComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive1_DataStoreComboBox = New-Object 'System.Windows.Forms.ComboBox'
	$ExtraDrive1_SizeLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive1_DatastoreLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive2_SizeLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive3_SizeLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive4_SizeLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive2_DatastoreLabel = New-Object 'System.Windows.Forms.Label'
	$ExtraDrive3_DatastoreLabel = New-Object 'System.Windows.Forms.Label'
	$ConfigureVMButton = New-Object 'System.Windows.Forms.Button'
	$CreateVMButton = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	Import-Module -Name VMware.VimAutomation.Core
	
	$Form_Load={
	#TODO: Initialize Form Controls here
	
	}
	
	
	#region Control Helper Functions
	function Load-ComboBox 
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
	
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
	
		.PARAMETER  ComboBox
			The ComboBox control you want to add items to.
	
		.PARAMETER  Items
			The object or objects you wish to load into the ComboBox's Items collection.
	
		.PARAMETER  DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER  Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red" -Append
			Load-ComboBox $combobox1 "White" -Append
			Load-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Load-ComboBox $combobox1 (Get-Process) "ProcessName"
	#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.ComboBox]$ComboBox,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Items,
		    [Parameter(Mandatory=$false)]
			[string]$DisplayMember,
			[switch]$Append
		)
		
		if(-not $Append)
		{
			$ComboBox.Items.Clear()	
		}
		
		if($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [Array])
		{
			$ComboBox.BeginUpdate()
			foreach($obj in $Items)
			{
				$ComboBox.Items.Add($obj)	
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)	
		}
	
		$ComboBox.DisplayMember = $DisplayMember	
	}
	#endregion
	
	
	$VCenterComboBox_SelectedIndexChanged={
		$Global:VMCreationSelections.VCenterServer = $($VCenterComboBox.SelectedItem)
		Write-Debug -Message "Server = $($Global:VMCreationSelections.VCenterServer)"
		Write-RichText -LogType 'Informational' -LogMsg "Connecting to $($Global:VMCreationSelections.VCenterServer) please be patient."
		$Script:Credentials = Get-Credential
		ConnectTo-VCenter
		
	}
	
	$LocalOfficeSelectionComboBox_SelectedIndexChanged={
		$Global:VMCreationSelections.Location = $($LocalOfficeSelectionComboBox.SelectedItem)
		Write-Debug -Message "Location = $($Global:VMCreationSelections.Location)"
		
		Write-RichText -LogType 'Informational' -LogMsg "Retrieving ESX Clusters please be patient."
		
		Populate-ESXClustersDropDown
		
	}
	
	$ESXClustersComboBox_SelectedIndexChanged={
		$Clusters = Get-Cluster -Server $Global:VMCreationSelections.VCenterServer `
								-location $Global:VMCreationSelections.Location `
								-Name $ESXClustersComboBox.SelectedItem
		If ($Clusters)
		{
			$Global:VMCreationSelections.ResourcePool = $Clusters
		}
		
		Else
		{
			$VMHosts = Get-VMHost -Server $Global:VMCreationSelections.VCenterServer `
								  -location $Global:VMCreationSelections.Location `
								  -Name $ESXClustersComboBox.SelectedItem
			
			$Global:VMCreationSelections.ResourcePool = $VMHosts
		}
		
		Write-Debug -Message "Location = $($Global:VMCreationSelections.ResourcePool)"
		Write-RichText -LogType 'Informational' -LogMsg "Retrieving Datastores please be patient."
		
		Populate-DatastoreClusterDropDown
		
	}
	
	$DataStoreClusterComboBox_SelectedIndexChanged={
		$DataStoreClusters = Get-DataStoreCluster -Server $Global:VMCreationSelections.VCenterServer `
												  -Location $Global:VMCreationSelections.Location `
												  -name $DataStoreClusterComboBox.SelectedItem
		
		If ($DataStoreClusters)
		{
			$Global:VMCreationSelections.Datastore = $DataStoreClusters
		}
		
		Else
		{
			$DataStores = Get-DataStore -Server $Global:VMCreationSelections.VCenterServer `
										-Location $Global:VMCreationSelections.Location `
										-name $DataStoreClusterComboBox.SelectedItem
			
			$Global:VMCreationSelections.Datastore = $DataStores
		}
		
		Write-Debug -Message "Location = $($Global:VMCreationSelections.DataStore)"
		Write-RichText -LogType 'Informational' -LogMsg "Retrieving Templates please be patient."
		
		Populate-TemplateDropDown
		
	}
	
	$TemplateSelectionComboBox_SelectedIndexChanged={
		$Global:VMCreationSelections.Template = Get-Template -Server $($Global:VMCreationSelections.VCenterServer) `
															 -Location $($Global:VMCreationSelections.Location) `
															 -Name $($TemplateSelectionComboBox.SelectedItem)
		
		
		Write-RichText -LogType 'Informational' -LogMsg "Retrieving Customizations please be patient."
		
		Populate-CustomizationDropDown
		
	}
	
	$VMnameInputBox_TextChanged={
		$Global:VMCreationSelections.Name = $VMnameInputBox.Text
		$CreateVMButton.Enabled = $True
		
	}
	
	$CreateVMButton_Click={
		$richtextbox1.clear()
		
		Write-RichText -LogType informational -LogMsg "VCenter server : $($Global:VMCreationSelections.VCenterServer)"
		Write-RichText -LogType informational -LogMsg "ESXCluster : $($Global:VMCreationSelections.ResourcePool)"
		Write-RichText -LogType informational -LogMsg "Location : $($Global:VMCreationSelections.Location)"
		Write-RichText -LogType informational -LogMsg "VM Name : $($Global:VMCreationSelections.Name)"
		Write-RichText -LogType informational -LogMsg "DataStore : $($Global:VMCreationSelections.Datastore)"
		Write-RichText -LogType informational -LogMsg "Template : $($Global:VMCreationSelections.Template)"
		Write-RichText -LogType informational -LogMsg "Customization : $($Global:VMCreationSelections.OSCustomizationSpec)"
		
		
		Write-RichText -LogType informational -LogMsg "VM Creation beginning please be patient."
		
		
		
		New-VM -Server $Global:VMCreationSelections.VCenterServer `
			   -ResourcePool $Global:VMCreationSelections.ResourcePool `
			   -Name $Global:VMCreationSelections.Name `
			   -Datastore $Global:VMCreationSelections.Datastore  `
			   -Template $Global:VMCreationSelections.Template `
			   -OSCustomizationSpec $Global:VMCreationSelections.OSCustomizationSpec
		
		Write-RichText -LogType informational -LogMsg "VM Creation Completed!"
		$VCPUsComboBox.Enabled = $True
		$RAMComboBox.Enabled = $True
		$domainupdown1.Enabled = $True
		$ConfigureVMButton.Enabled = $true
		
	}
	
	$CustomizationSelectioncomboBox_SelectedIndexChanged={
		
		$Global:VMCreationSelections.OSCustomizationSpec = Get-OSCustomizationSpec -Server $Global:VMCreationSelections.VCenterServer `
																				   -Name $CustomizationSelectioncomboBox.SelectedItem
		
		$VMnameInputBox.Enabled = $true
	}
	
	$ExtraDriveCounter_ValueChanged={
		switch ($ExtraDriveCounter.Value)
		{
			0 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $false
				$ExtraDrive1_letterComboBox.enabled = $false
				$ExtraDrive1_SizeTextBox.enabled = $false
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $false
				$ExtraDrive2_letterComboBox.enabled = $false
				$ExtraDrive2_SizeTextBox.enabled = $false
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $false
				$ExtraDrive3_letterComboBox.enabled = $false
				$ExtraDrive3_SizeTextBox.enabled = $false
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SizeTextBox.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SizeTextBox.enabled = $false
			}
			1 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SizeTextBox.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $false
				$ExtraDrive2_letterComboBox.enabled = $false
				$ExtraDrive2_SizeTextBox.enabled = $false
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $false
				$ExtraDrive3_letterComboBox.enabled = $false
				$ExtraDrive3_SizeTextBox.enabled = $false
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SizeTextBox.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SizeTextBox.enabled = $false
			}
			2 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SizeTextBox.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SizeTextBox.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $false
				$ExtraDrive3_letterComboBox.enabled = $false
				$ExtraDrive3_SizeTextBox.enabled = $false
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SizeTextBox.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SizeTextBox.enabled = $false
			}
			3 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SizeTextBox.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SizeTextBox.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $true
				$ExtraDrive3_letterComboBox.enabled = $true
				$ExtraDrive3_SizeTextBox.enabled = $true
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SizeTextBox.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SizeTextBox.enabled = $false
			}
			4 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SizeTextBox.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SizeTextBox.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $true
				$ExtraDrive3_letterComboBox.enabled = $true
				$ExtraDrive3_SizeTextBox.enabled = $true
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $true
				$ExtraDrive4_letterComboBox.enabled = $true
				$ExtraDrive4_SizeTextBox.enabled = $true
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SizeTextBox.enabled = $false
			}
			5{
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SizeTextBox.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SizeTextBox.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $true
				$ExtraDrive3_letterComboBox.enabled = $true
				$ExtraDrive3_SizeTextBox.enabled = $true
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $true
				$ExtraDrive4_letterComboBox.enabled = $true
				$ExtraDrive4_SizeTextBox.enabled = $true
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $true
				$ExtraDrive5_letterComboBox.enabled = $true
				$ExtraDrive5_SizeTextBox.enabled = $true
			}
		}
		
	}
	
	$ConfigureVMButton_Click={
		Set-VMCPUCount
		Set-VMRamAmount
		Add-VMDIsks
	}
	
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$Form.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_richtextbox1 = $richtextbox1.Text
		$script:MainForm_ExtraDriveCounter = $ExtraDriveCounter.Value
		$script:MainForm_DriveInfoTextBox = $DriveInfoTextBox.Text
		$script:MainForm_RAMComboBox = $RAMComboBox.Text
		$script:MainForm_RAMComboBox_SelectedItem = $RAMComboBox.SelectedItem
		$script:MainForm_VCPUsComboBox = $VCPUsComboBox.Text
		$script:MainForm_VCPUsComboBox_SelectedItem = $VCPUsComboBox.SelectedItem
		$script:MainForm_VMnameInputBox = $VMnameInputBox.Text
		$script:MainForm_CustomizationSelectioncomboBox = $CustomizationSelectioncomboBox.Text
		$script:MainForm_CustomizationSelectioncomboBox_SelectedItem = $CustomizationSelectioncomboBox.SelectedItem
		$script:MainForm_TemplateSelectionComboBox = $TemplateSelectionComboBox.Text
		$script:MainForm_TemplateSelectionComboBox_SelectedItem = $TemplateSelectionComboBox.SelectedItem
		$script:MainForm_DataStoreClusterComboBox = $DataStoreClusterComboBox.Text
		$script:MainForm_DataStoreClusterComboBox_SelectedItem = $DataStoreClusterComboBox.SelectedItem
		$script:MainForm_ESXClustersComboBox = $ESXClustersComboBox.Text
		$script:MainForm_ESXClustersComboBox_SelectedItem = $ESXClustersComboBox.SelectedItem
		$script:MainForm_LocalOfficeSelectionComboBox = $LocalOfficeSelectionComboBox.Text
		$script:MainForm_LocalOfficeSelectionComboBox_SelectedItem = $LocalOfficeSelectionComboBox.SelectedItem
		$script:MainForm_VCenterComboBox = $VCenterComboBox.Text
		$script:MainForm_VCenterComboBox_SelectedItem = $VCenterComboBox.SelectedItem
		$script:MainForm_ExtraDrive5_SizeTextBox = $ExtraDrive5_SizeTextBox.Text
		$script:MainForm_ExtraDrive4_SizeTextBox = $ExtraDrive4_SizeTextBox.Text
		$script:MainForm_ExtraDrive3_SizeTextBox = $ExtraDrive3_SizeTextBox.Text
		$script:MainForm_ExtraDrive2_SizeTextBox = $ExtraDrive2_SizeTextBox.Text
		$script:MainForm_ExtraDrive1_SizeTextBox = $ExtraDrive1_SizeTextBox.Text
		$script:MainForm_ExtraDrive5_DataStoreComboBox = $ExtraDrive5_DataStoreComboBox.Text
		$script:MainForm_ExtraDrive5_DataStoreComboBox_SelectedItem = $ExtraDrive5_DataStoreComboBox.SelectedItem
		$script:MainForm_ExtraDrive5_letterComboBox = $ExtraDrive5_letterComboBox.Text
		$script:MainForm_ExtraDrive5_letterComboBox_SelectedItem = $ExtraDrive5_letterComboBox.SelectedItem
		$script:MainForm_ExtraDrive4_letterComboBox = $ExtraDrive4_letterComboBox.Text
		$script:MainForm_ExtraDrive4_letterComboBox_SelectedItem = $ExtraDrive4_letterComboBox.SelectedItem
		$script:MainForm_ExtraDrive4_DataStoreComboBox = $ExtraDrive4_DataStoreComboBox.Text
		$script:MainForm_ExtraDrive4_DataStoreComboBox_SelectedItem = $ExtraDrive4_DataStoreComboBox.SelectedItem
		$script:MainForm_ExtraDrive3_letterComboBox = $ExtraDrive3_letterComboBox.Text
		$script:MainForm_ExtraDrive3_letterComboBox_SelectedItem = $ExtraDrive3_letterComboBox.SelectedItem
		$script:MainForm_ExtraDrive2_letterComboBox = $ExtraDrive2_letterComboBox.Text
		$script:MainForm_ExtraDrive2_letterComboBox_SelectedItem = $ExtraDrive2_letterComboBox.SelectedItem
		$script:MainForm_ExtraDrive1_letterComboBox = $ExtraDrive1_letterComboBox.Text
		$script:MainForm_ExtraDrive1_letterComboBox_SelectedItem = $ExtraDrive1_letterComboBox.SelectedItem
		$script:MainForm_ExtraDrive3_DataStoreComboBox = $ExtraDrive3_DataStoreComboBox.Text
		$script:MainForm_ExtraDrive3_DataStoreComboBox_SelectedItem = $ExtraDrive3_DataStoreComboBox.SelectedItem
		$script:MainForm_ExtraDrive2_DataStoreComboBox = $ExtraDrive2_DataStoreComboBox.Text
		$script:MainForm_ExtraDrive2_DataStoreComboBox_SelectedItem = $ExtraDrive2_DataStoreComboBox.SelectedItem
		$script:MainForm_ExtraDrive1_DataStoreComboBox = $ExtraDrive1_DataStoreComboBox.Text
		$script:MainForm_ExtraDrive1_DataStoreComboBox_SelectedItem = $ExtraDrive1_DataStoreComboBox.SelectedItem
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$ExtraDriveCounter.remove_ValueChanged($ExtraDriveCounter_ValueChanged)
			$VMnameInputBox.remove_TextChanged($VMnameInputBox_TextChanged)
			$CustomizationSelectioncomboBox.remove_SelectedIndexChanged($CustomizationSelectioncomboBox_SelectedIndexChanged)
			$TemplateSelectionComboBox.remove_SelectedIndexChanged($TemplateSelectionComboBox_SelectedIndexChanged)
			$DataStoreClusterComboBox.remove_SelectedIndexChanged($DataStoreClusterComboBox_SelectedIndexChanged)
			$ESXClustersComboBox.remove_SelectedIndexChanged($ESXClustersComboBox_SelectedIndexChanged)
			$LocalOfficeSelectionComboBox.remove_SelectedIndexChanged($LocalOfficeSelectionComboBox_SelectedIndexChanged)
			$VCenterComboBox.remove_SelectedIndexChanged($VCenterComboBox_SelectedIndexChanged)
			$ConfigureVMButton.remove_Click($ConfigureVMButton_Click)
			$CreateVMButton.remove_Click($CreateVMButton_Click)
			$Form.remove_Load($Form_Load)
			$Form.remove_Load($Form_StateCorrection_Load)
			$Form.remove_Closing($Form_StoreValues_Closing)
			$Form.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$Form.SuspendLayout()
	$groupbox10.SuspendLayout()
	$ExtraDriveCounter.BeginInit()
	$groupbox9.SuspendLayout()
	$groupbox8.SuspendLayout()
	$groupbox7.SuspendLayout()
	$groupbox6.SuspendLayout()
	$groupbox5.SuspendLayout()
	$groupbox4.SuspendLayout()
	$groupbox2.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# Form
	#
	$Form.Controls.Add($richtextbox1)
	$Form.Controls.Add($groupbox10)
	$Form.Controls.Add($groupbox9)
	$Form.Controls.Add($groupbox8)
	$Form.Controls.Add($groupbox7)
	$Form.Controls.Add($groupbox6)
	$Form.Controls.Add($groupbox5)
	$Form.Controls.Add($groupbox4)
	$Form.Controls.Add($groupbox2)
	$Form.Controls.Add($groupbox1)
	$Form.Controls.Add($ConfigureVMButton)
	$Form.Controls.Add($CreateVMButton)
	$Form.BackColor = 'ActiveCaption'
	$Form.ClientSize = '1268, 843'
	$Form.Name = 'Form'
	$Form.StartPosition = 'CenterScreen'
	$Form.Text = 'Main Form'
	$Form.add_Load($Form_Load)
	#
	# richtextbox1
	#
	$richtextbox1.Location = '5, 657'
	$richtextbox1.Name = 'richtextbox1'
	$richtextbox1.Size = '1251, 174'
	$richtextbox1.TabIndex = 62
	$richtextbox1.Text = ''
	#
	# groupbox10
	#
	$groupbox10.Controls.Add($ExtraDriveCounter)
	$groupbox10.Controls.Add($DriveInfoTextBox)
	$groupbox10.Controls.Add($RAMComboBox)
	$groupbox10.Controls.Add($RAMSelectionLabel)
	$groupbox10.Controls.Add($VCPUsComboBox)
	$groupbox10.Controls.Add($VCPUsSelectionLabel)
	$groupbox10.Location = '350, 5'
	$groupbox10.Name = 'groupbox10'
	$groupbox10.Size = '343, 250'
	$groupbox10.TabIndex = 61
	$groupbox10.TabStop = $False
	#
	# ExtraDriveCounter
	#
	$ExtraDriveCounter.Location = '268, 160'
	$ExtraDriveCounter.Maximum = 5
	$ExtraDriveCounter.Name = 'ExtraDriveCounter'
	$ExtraDriveCounter.ReadOnly = $True
	$ExtraDriveCounter.Size = '51, 23'
	$ExtraDriveCounter.TabIndex = 20
	$ExtraDriveCounter.add_ValueChanged($ExtraDriveCounter_ValueChanged)
	#
	# DriveInfoTextBox
	#
	$DriveInfoTextBox.BackColor = 'ControlLight'
	$DriveInfoTextBox.Location = '5, 160'
	$DriveInfoTextBox.Multiline = $True
	$DriveInfoTextBox.Name = 'DriveInfoTextBox'
	$DriveInfoTextBox.ReadOnly = $True
	$DriveInfoTextBox.Size = '257, 82'
	$DriveInfoTextBox.TabIndex = 19
	$DriveInfoTextBox.Text = 'The ''C'', ''D'', and ''P'' drives are automatically created. Please choose how many extra drives you need for this VM.'
	#
	# RAMComboBox
	#
	$RAMComboBox.DropDownStyle = 'DropDownList'
	$RAMComboBox.Enabled = $False
	$RAMComboBox.FormattingEnabled = $True
	[void]$RAMComboBox.Items.Add('2')
	[void]$RAMComboBox.Items.Add('4')
	[void]$RAMComboBox.Items.Add('8')
	[void]$RAMComboBox.Items.Add('16')
	[void]$RAMComboBox.Items.Add('32')
	[void]$RAMComboBox.Items.Add('64')
	[void]$RAMComboBox.Items.Add('128')
	[void]$RAMComboBox.Items.Add('256')
	$RAMComboBox.Location = '5, 104'
	$RAMComboBox.Name = 'RAMComboBox'
	$RAMComboBox.Size = '315, 25'
	$RAMComboBox.TabIndex = 18
	#
	# RAMSelectionLabel
	#
	$RAMSelectionLabel.Location = '5, 75'
	$RAMSelectionLabel.Margin = '3, 3, 3, 3'
	$RAMSelectionLabel.Name = 'RAMSelectionLabel'
	$RAMSelectionLabel.Size = '315, 20'
	$RAMSelectionLabel.TabIndex = 17
	$RAMSelectionLabel.Text = 'Please Select the desired amount of RAM (GB)'
	#
	# VCPUsComboBox
	#
	$VCPUsComboBox.DropDownStyle = 'DropDownList'
	$VCPUsComboBox.Enabled = $False
	$VCPUsComboBox.FormattingEnabled = $True
	[void]$VCPUsComboBox.Items.Add('2')
	[void]$VCPUsComboBox.Items.Add('4')
	[void]$VCPUsComboBox.Items.Add('8')
	[void]$VCPUsComboBox.Items.Add('16')
	[void]$VCPUsComboBox.Items.Add('32')
	$VCPUsComboBox.Location = '5, 47'
	$VCPUsComboBox.Name = 'VCPUsComboBox'
	$VCPUsComboBox.Size = '315, 25'
	$VCPUsComboBox.TabIndex = 16
	#
	# VCPUsSelectionLabel
	#
	$VCPUsSelectionLabel.Location = '5, 22'
	$VCPUsSelectionLabel.Margin = '3, 3, 3, 3'
	$VCPUsSelectionLabel.Name = 'VCPUsSelectionLabel'
	$VCPUsSelectionLabel.Size = '315, 20'
	$VCPUsSelectionLabel.TabIndex = 15
	$VCPUsSelectionLabel.Text = 'Please Select the Desired Number of Cores'
	#
	# groupbox9
	#
	$groupbox9.Controls.Add($VMnameInputBox)
	$groupbox9.Controls.Add($VMnameInputBoxLabel)
	$groupbox9.Location = '0, 515'
	$groupbox9.Name = 'groupbox9'
	$groupbox9.Size = '330, 80'
	$groupbox9.TabIndex = 60
	$groupbox9.TabStop = $False
	#
	# VMnameInputBox
	#
	$VMnameInputBox.Enabled = $False
	$VMnameInputBox.Location = '5, 47'
	$VMnameInputBox.Name = 'VMnameInputBox'
	$VMnameInputBox.Size = '293, 23'
	$VMnameInputBox.TabIndex = 13
	$VMnameInputBox.add_TextChanged($VMnameInputBox_TextChanged)
	#
	# VMnameInputBoxLabel
	#
	$VMnameInputBoxLabel.Location = '5, 22'
	$VMnameInputBoxLabel.Margin = '3, 3, 3, 3'
	$VMnameInputBoxLabel.Name = 'VMnameInputBoxLabel'
	$VMnameInputBoxLabel.Size = '293, 30'
	$VMnameInputBoxLabel.TabIndex = 12
	$VMnameInputBoxLabel.Text = 'Please Enter the Desired VM Name'
	#
	# groupbox8
	#
	$groupbox8.Controls.Add($CustomizationSelectioncomboBox)
	$groupbox8.Controls.Add($CustomizationSelectionLabel)
	$groupbox8.Location = '0, 430'
	$groupbox8.Name = 'groupbox8'
	$groupbox8.Size = '330, 80'
	$groupbox8.TabIndex = 59
	$groupbox8.TabStop = $False
	#
	# CustomizationSelectioncomboBox
	#
	$CustomizationSelectioncomboBox.DropDownStyle = 'DropDownList'
	$CustomizationSelectioncomboBox.Enabled = $False
	$CustomizationSelectioncomboBox.FormattingEnabled = $True
	$CustomizationSelectioncomboBox.Location = '5, 47'
	$CustomizationSelectioncomboBox.Name = 'CustomizationSelectioncomboBox'
	$CustomizationSelectioncomboBox.Size = '293, 25'
	$CustomizationSelectioncomboBox.TabIndex = 11
	$CustomizationSelectioncomboBox.add_SelectedIndexChanged($CustomizationSelectioncomboBox_SelectedIndexChanged)
	#
	# CustomizationSelectionLabel
	#
	$CustomizationSelectionLabel.Location = '5, 22'
	$CustomizationSelectionLabel.Margin = '3, 3, 3, 3'
	$CustomizationSelectionLabel.Name = 'CustomizationSelectionLabel'
	$CustomizationSelectionLabel.Size = '293, 30'
	$CustomizationSelectionLabel.TabIndex = 10
	$CustomizationSelectionLabel.Text = 'Please Select the Customization'
	#
	# groupbox7
	#
	$groupbox7.Controls.Add($TemplateSelectionComboBox)
	$groupbox7.Controls.Add($TemplateSelectionLabel)
	$groupbox7.Location = '0, 345'
	$groupbox7.Name = 'groupbox7'
	$groupbox7.Size = '330, 80'
	$groupbox7.TabIndex = 58
	$groupbox7.TabStop = $False
	#
	# TemplateSelectionComboBox
	#
	$TemplateSelectionComboBox.DropDownStyle = 'DropDownList'
	$TemplateSelectionComboBox.Enabled = $False
	$TemplateSelectionComboBox.FormattingEnabled = $True
	$TemplateSelectionComboBox.Location = '5, 47'
	$TemplateSelectionComboBox.Name = 'TemplateSelectionComboBox'
	$TemplateSelectionComboBox.Size = '293, 25'
	$TemplateSelectionComboBox.TabIndex = 9
	$TemplateSelectionComboBox.add_SelectedIndexChanged($TemplateSelectionComboBox_SelectedIndexChanged)
	#
	# TemplateSelectionLabel
	#
	$TemplateSelectionLabel.Location = '5, 22'
	$TemplateSelectionLabel.Margin = '3, 3, 3, 3'
	$TemplateSelectionLabel.Name = 'TemplateSelectionLabel'
	$TemplateSelectionLabel.Size = '293, 30'
	$TemplateSelectionLabel.TabIndex = 8
	$TemplateSelectionLabel.Text = 'Please Select the Template'
	#
	# groupbox6
	#
	$groupbox6.Controls.Add($DataStoreClusterComboBox)
	$groupbox6.Controls.Add($DataStoreClusterSelectionLabel)
	$groupbox6.Location = '0, 260'
	$groupbox6.Name = 'groupbox6'
	$groupbox6.Size = '330, 80'
	$groupbox6.TabIndex = 57
	$groupbox6.TabStop = $False
	#
	# DataStoreClusterComboBox
	#
	$DataStoreClusterComboBox.DropDownStyle = 'DropDownList'
	$DataStoreClusterComboBox.Enabled = $False
	$DataStoreClusterComboBox.FormattingEnabled = $True
	$DataStoreClusterComboBox.Location = '5, 47'
	$DataStoreClusterComboBox.Name = 'DataStoreClusterComboBox'
	$DataStoreClusterComboBox.Size = '293, 25'
	$DataStoreClusterComboBox.TabIndex = 7
	$DataStoreClusterComboBox.add_SelectedIndexChanged($DataStoreClusterComboBox_SelectedIndexChanged)
	#
	# DataStoreClusterSelectionLabel
	#
	$DataStoreClusterSelectionLabel.Location = '5, 22'
	$DataStoreClusterSelectionLabel.Margin = '3, 3, 3, 3'
	$DataStoreClusterSelectionLabel.Name = 'DataStoreClusterSelectionLabel'
	$DataStoreClusterSelectionLabel.Size = '293, 23'
	$DataStoreClusterSelectionLabel.TabIndex = 6
	$DataStoreClusterSelectionLabel.Text = 'Please Select the Datastore or Cluster'
	#
	# groupbox5
	#
	$groupbox5.Controls.Add($ESXClustersComboBox)
	$groupbox5.Controls.Add($ESXHostsSelectionLabel)
	$groupbox5.Location = '0, 175'
	$groupbox5.Name = 'groupbox5'
	$groupbox5.Size = '330, 80'
	$groupbox5.TabIndex = 56
	$groupbox5.TabStop = $False
	#
	# ESXClustersComboBox
	#
	$ESXClustersComboBox.DropDownStyle = 'DropDownList'
	$ESXClustersComboBox.Enabled = $False
	$ESXClustersComboBox.FormattingEnabled = $True
	$ESXClustersComboBox.Location = '5, 47'
	$ESXClustersComboBox.Name = 'ESXClustersComboBox'
	$ESXClustersComboBox.Size = '295, 25'
	$ESXClustersComboBox.TabIndex = 5
	$ESXClustersComboBox.add_SelectedIndexChanged($ESXClustersComboBox_SelectedIndexChanged)
	#
	# ESXHostsSelectionLabel
	#
	$ESXHostsSelectionLabel.Location = '5, 22'
	$ESXHostsSelectionLabel.Margin = '3, 3, 3, 3'
	$ESXHostsSelectionLabel.Name = 'ESXHostsSelectionLabel'
	$ESXHostsSelectionLabel.Size = '295, 20'
	$ESXHostsSelectionLabel.TabIndex = 4
	$ESXHostsSelectionLabel.Text = 'Please Select the ESX Host or Cluster'
	#
	# groupbox4
	#
	$groupbox4.Controls.Add($LocalOfficeSelectionComboBox)
	$groupbox4.Controls.Add($LocalOfficeSelectionLabel)
	$groupbox4.Location = '0, 90'
	$groupbox4.Name = 'groupbox4'
	$groupbox4.Size = '330, 80'
	$groupbox4.TabIndex = 55
	$groupbox4.TabStop = $False
	#
	# LocalOfficeSelectionComboBox
	#
	$LocalOfficeSelectionComboBox.DropDownStyle = 'DropDownList'
	$LocalOfficeSelectionComboBox.Enabled = $False
	$LocalOfficeSelectionComboBox.FormattingEnabled = $True
	$LocalOfficeSelectionComboBox.Location = '5, 47'
	$LocalOfficeSelectionComboBox.Name = 'LocalOfficeSelectionComboBox'
	$LocalOfficeSelectionComboBox.Size = '295, 25'
	$LocalOfficeSelectionComboBox.TabIndex = 3
	$LocalOfficeSelectionComboBox.add_SelectedIndexChanged($LocalOfficeSelectionComboBox_SelectedIndexChanged)
	#
	# LocalOfficeSelectionLabel
	#
	$LocalOfficeSelectionLabel.Location = '5, 22'
	$LocalOfficeSelectionLabel.Margin = '3, 3, 3, 3'
	$LocalOfficeSelectionLabel.Name = 'LocalOfficeSelectionLabel'
	$LocalOfficeSelectionLabel.Size = '295, 20'
	$LocalOfficeSelectionLabel.TabIndex = 2
	$LocalOfficeSelectionLabel.Text = 'Please Select the Local Office or Datacenter'
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($VCenterComboBox)
	$groupbox2.Controls.Add($VCenterSelection)
	$groupbox2.Location = '0, 5'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '330, 80'
	$groupbox2.TabIndex = 53
	$groupbox2.TabStop = $False
	#
	# VCenterComboBox
	#
	$VCenterComboBox.DropDownStyle = 'DropDownList'
	$VCenterComboBox.FormattingEnabled = $True
	[void]$VCenterComboBox.Items.Add('AM1-VCenter')
	[void]$VCenterComboBox.Items.Add('AP1-VCenter')
	[void]$VCenterComboBox.Items.Add('EM1-VCenter')
	$VCenterComboBox.Location = '5, 47'
	$VCenterComboBox.Name = 'VCenterComboBox'
	$VCenterComboBox.Size = '295, 25'
	$VCenterComboBox.TabIndex = 1
	$VCenterComboBox.add_SelectedIndexChanged($VCenterComboBox_SelectedIndexChanged)
	#
	# VCenterSelection
	#
	$VCenterSelection.Location = '5, 22'
	$VCenterSelection.Margin = '3, 3, 3, 3'
	$VCenterSelection.Name = 'VCenterSelection'
	$VCenterSelection.Size = '295, 20'
	$VCenterSelection.TabIndex = 0
	$VCenterSelection.Text = 'Please Select the VCenter Region'
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($ExtraDrive5_SizeTextBox)
	$groupbox1.Controls.Add($ExtraDrive4_SizeTextBox)
	$groupbox1.Controls.Add($ExtraDrive3_SizeTextBox)
	$groupbox1.Controls.Add($ExtraDrive2_SizeTextBox)
	$groupbox1.Controls.Add($ExtraDrive1_SizeTextBox)
	$groupbox1.Controls.Add($ExtraDrive5_DataStoreComboBox)
	$groupbox1.Controls.Add($ExtraDrive5_letterComboBox)
	$groupbox1.Controls.Add($ExtraDrive5_SelectionLabel)
	$groupbox1.Controls.Add($ExtraDrive5_DatastoreLabel)
	$groupbox1.Controls.Add($ExtraDrive4_letterComboBox)
	$groupbox1.Controls.Add($ExtraDrive4_SelectionLabel)
	$groupbox1.Controls.Add($ExtraDrive5_SizeLabel)
	$groupbox1.Controls.Add($ExtraDrive4_DataStoreComboBox)
	$groupbox1.Controls.Add($ExtraDrive3_letterComboBox)
	$groupbox1.Controls.Add($ExtraDrive3_SelectionLabel)
	$groupbox1.Controls.Add($ExtraDrive2_letterComboBox)
	$groupbox1.Controls.Add($ExtraDrive2_SelectionLabel)
	$groupbox1.Controls.Add($ExtraDrive1_letterComboBox)
	$groupbox1.Controls.Add($ExtraDrive1_SelectionLabel)
	$groupbox1.Controls.Add($ExtraDrive3_DataStoreComboBox)
	$groupbox1.Controls.Add($ExtraDrive4_DatastoreLabel)
	$groupbox1.Controls.Add($ExtraDrive2_DataStoreComboBox)
	$groupbox1.Controls.Add($ExtraDrive1_DataStoreComboBox)
	$groupbox1.Controls.Add($ExtraDrive1_SizeLabel)
	$groupbox1.Controls.Add($ExtraDrive1_DatastoreLabel)
	$groupbox1.Controls.Add($ExtraDrive2_SizeLabel)
	$groupbox1.Controls.Add($ExtraDrive3_SizeLabel)
	$groupbox1.Controls.Add($ExtraDrive4_SizeLabel)
	$groupbox1.Controls.Add($ExtraDrive2_DatastoreLabel)
	$groupbox1.Controls.Add($ExtraDrive3_DatastoreLabel)
	$groupbox1.Location = '350, 261'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '390, 334'
	$groupbox1.TabIndex = 52
	$groupbox1.TabStop = $False
	#
	# ExtraDrive5_SizeTextBox
	#
	$ExtraDrive5_SizeTextBox.Enabled = $False
	$ExtraDrive5_SizeTextBox.Location = '65, 290'
	$ExtraDrive5_SizeTextBox.Name = 'ExtraDrive5_SizeTextBox'
	$ExtraDrive5_SizeTextBox.Size = '100, 23'
	$ExtraDrive5_SizeTextBox.TabIndex = 55
	#
	# ExtraDrive4_SizeTextBox
	#
	$ExtraDrive4_SizeTextBox.Enabled = $False
	$ExtraDrive4_SizeTextBox.Location = '65, 230'
	$ExtraDrive4_SizeTextBox.Name = 'ExtraDrive4_SizeTextBox'
	$ExtraDrive4_SizeTextBox.Size = '100, 23'
	$ExtraDrive4_SizeTextBox.TabIndex = 54
	#
	# ExtraDrive3_SizeTextBox
	#
	$ExtraDrive3_SizeTextBox.Enabled = $False
	$ExtraDrive3_SizeTextBox.Location = '65, 170'
	$ExtraDrive3_SizeTextBox.Name = 'ExtraDrive3_SizeTextBox'
	$ExtraDrive3_SizeTextBox.Size = '100, 23'
	$ExtraDrive3_SizeTextBox.TabIndex = 53
	#
	# ExtraDrive2_SizeTextBox
	#
	$ExtraDrive2_SizeTextBox.Enabled = $False
	$ExtraDrive2_SizeTextBox.Location = '65, 110'
	$ExtraDrive2_SizeTextBox.Name = 'ExtraDrive2_SizeTextBox'
	$ExtraDrive2_SizeTextBox.Size = '100, 23'
	$ExtraDrive2_SizeTextBox.TabIndex = 52
	#
	# ExtraDrive1_SizeTextBox
	#
	$ExtraDrive1_SizeTextBox.Enabled = $False
	$ExtraDrive1_SizeTextBox.Location = '65, 50'
	$ExtraDrive1_SizeTextBox.Name = 'ExtraDrive1_SizeTextBox'
	$ExtraDrive1_SizeTextBox.Size = '100, 23'
	$ExtraDrive1_SizeTextBox.TabIndex = 51
	#
	# ExtraDrive5_DataStoreComboBox
	#
	$ExtraDrive5_DataStoreComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive5_DataStoreComboBox.Enabled = $False
	$ExtraDrive5_DataStoreComboBox.FormattingEnabled = $True
	$ExtraDrive5_DataStoreComboBox.Location = '171, 290'
	$ExtraDrive5_DataStoreComboBox.Name = 'ExtraDrive5_DataStoreComboBox'
	$ExtraDrive5_DataStoreComboBox.Size = '198, 25'
	$ExtraDrive5_DataStoreComboBox.TabIndex = 50
	#
	# ExtraDrive5_letterComboBox
	#
	$ExtraDrive5_letterComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive5_letterComboBox.Enabled = $False
	$ExtraDrive5_letterComboBox.FormattingEnabled = $True
	[void]$ExtraDrive5_letterComboBox.Items.Add('A')
	[void]$ExtraDrive5_letterComboBox.Items.Add('B')
	[void]$ExtraDrive5_letterComboBox.Items.Add('E')
	[void]$ExtraDrive5_letterComboBox.Items.Add('F')
	[void]$ExtraDrive5_letterComboBox.Items.Add('G')
	[void]$ExtraDrive5_letterComboBox.Items.Add('H')
	[void]$ExtraDrive5_letterComboBox.Items.Add('I')
	[void]$ExtraDrive5_letterComboBox.Items.Add('J')
	[void]$ExtraDrive5_letterComboBox.Items.Add('K')
	[void]$ExtraDrive5_letterComboBox.Items.Add('L')
	[void]$ExtraDrive5_letterComboBox.Items.Add('M')
	[void]$ExtraDrive5_letterComboBox.Items.Add('N')
	[void]$ExtraDrive5_letterComboBox.Items.Add('O')
	[void]$ExtraDrive5_letterComboBox.Items.Add('Q')
	[void]$ExtraDrive5_letterComboBox.Items.Add('R')
	[void]$ExtraDrive5_letterComboBox.Items.Add('S')
	[void]$ExtraDrive5_letterComboBox.Items.Add('T')
	[void]$ExtraDrive5_letterComboBox.Items.Add('U')
	[void]$ExtraDrive5_letterComboBox.Items.Add('V')
	[void]$ExtraDrive5_letterComboBox.Items.Add('W')
	[void]$ExtraDrive5_letterComboBox.Items.Add('X')
	[void]$ExtraDrive5_letterComboBox.Items.Add('Y')
	[void]$ExtraDrive5_letterComboBox.Items.Add('Z')
	$ExtraDrive5_letterComboBox.Location = '6, 290'
	$ExtraDrive5_letterComboBox.Name = 'ExtraDrive5_letterComboBox'
	$ExtraDrive5_letterComboBox.Size = '41, 25'
	$ExtraDrive5_letterComboBox.TabIndex = 46
	#
	# ExtraDrive5_SelectionLabel
	#
	$ExtraDrive5_SelectionLabel.Location = '6, 260'
	$ExtraDrive5_SelectionLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive5_SelectionLabel.Name = 'ExtraDrive5_SelectionLabel'
	$ExtraDrive5_SelectionLabel.Size = '41, 23'
	$ExtraDrive5_SelectionLabel.TabIndex = 45
	$ExtraDrive5_SelectionLabel.Text = 'Drive'
	#
	# ExtraDrive5_DatastoreLabel
	#
	$ExtraDrive5_DatastoreLabel.Location = '171, 260'
	$ExtraDrive5_DatastoreLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive5_DatastoreLabel.Name = 'ExtraDrive5_DatastoreLabel'
	$ExtraDrive5_DatastoreLabel.Size = '100, 23'
	$ExtraDrive5_DatastoreLabel.TabIndex = 49
	$ExtraDrive5_DatastoreLabel.Text = 'Datastore'
	#
	# ExtraDrive4_letterComboBox
	#
	$ExtraDrive4_letterComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive4_letterComboBox.Enabled = $False
	$ExtraDrive4_letterComboBox.FormattingEnabled = $True
	[void]$ExtraDrive4_letterComboBox.Items.Add('A')
	[void]$ExtraDrive4_letterComboBox.Items.Add('B')
	[void]$ExtraDrive4_letterComboBox.Items.Add('E')
	[void]$ExtraDrive4_letterComboBox.Items.Add('F')
	[void]$ExtraDrive4_letterComboBox.Items.Add('G')
	[void]$ExtraDrive4_letterComboBox.Items.Add('H')
	[void]$ExtraDrive4_letterComboBox.Items.Add('I')
	[void]$ExtraDrive4_letterComboBox.Items.Add('J')
	[void]$ExtraDrive4_letterComboBox.Items.Add('K')
	[void]$ExtraDrive4_letterComboBox.Items.Add('L')
	[void]$ExtraDrive4_letterComboBox.Items.Add('M')
	[void]$ExtraDrive4_letterComboBox.Items.Add('N')
	[void]$ExtraDrive4_letterComboBox.Items.Add('O')
	[void]$ExtraDrive4_letterComboBox.Items.Add('Q')
	[void]$ExtraDrive4_letterComboBox.Items.Add('R')
	[void]$ExtraDrive4_letterComboBox.Items.Add('S')
	[void]$ExtraDrive4_letterComboBox.Items.Add('T')
	[void]$ExtraDrive4_letterComboBox.Items.Add('U')
	[void]$ExtraDrive4_letterComboBox.Items.Add('V')
	[void]$ExtraDrive4_letterComboBox.Items.Add('W')
	[void]$ExtraDrive4_letterComboBox.Items.Add('X')
	[void]$ExtraDrive4_letterComboBox.Items.Add('Y')
	[void]$ExtraDrive4_letterComboBox.Items.Add('Z')
	$ExtraDrive4_letterComboBox.Location = '6, 230'
	$ExtraDrive4_letterComboBox.Name = 'ExtraDrive4_letterComboBox'
	$ExtraDrive4_letterComboBox.Size = '41, 25'
	$ExtraDrive4_letterComboBox.TabIndex = 40
	#
	# ExtraDrive4_SelectionLabel
	#
	$ExtraDrive4_SelectionLabel.Location = '6, 200'
	$ExtraDrive4_SelectionLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive4_SelectionLabel.Name = 'ExtraDrive4_SelectionLabel'
	$ExtraDrive4_SelectionLabel.Size = '41, 23'
	$ExtraDrive4_SelectionLabel.TabIndex = 39
	$ExtraDrive4_SelectionLabel.Text = 'Drive'
	#
	# ExtraDrive5_SizeLabel
	#
	$ExtraDrive5_SizeLabel.Location = '65, 260'
	$ExtraDrive5_SizeLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive5_SizeLabel.Name = 'ExtraDrive5_SizeLabel'
	$ExtraDrive5_SizeLabel.Size = '100, 23'
	$ExtraDrive5_SizeLabel.TabIndex = 48
	$ExtraDrive5_SizeLabel.Text = 'Size (GB)'
	#
	# ExtraDrive4_DataStoreComboBox
	#
	$ExtraDrive4_DataStoreComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive4_DataStoreComboBox.Enabled = $False
	$ExtraDrive4_DataStoreComboBox.FormattingEnabled = $True
	$ExtraDrive4_DataStoreComboBox.Location = '171, 230'
	$ExtraDrive4_DataStoreComboBox.Name = 'ExtraDrive4_DataStoreComboBox'
	$ExtraDrive4_DataStoreComboBox.Size = '198, 25'
	$ExtraDrive4_DataStoreComboBox.TabIndex = 44
	#
	# ExtraDrive3_letterComboBox
	#
	$ExtraDrive3_letterComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive3_letterComboBox.Enabled = $False
	$ExtraDrive3_letterComboBox.FormattingEnabled = $True
	[void]$ExtraDrive3_letterComboBox.Items.Add('A')
	[void]$ExtraDrive3_letterComboBox.Items.Add('B')
	[void]$ExtraDrive3_letterComboBox.Items.Add('E')
	[void]$ExtraDrive3_letterComboBox.Items.Add('F')
	[void]$ExtraDrive3_letterComboBox.Items.Add('G')
	[void]$ExtraDrive3_letterComboBox.Items.Add('H')
	[void]$ExtraDrive3_letterComboBox.Items.Add('I')
	[void]$ExtraDrive3_letterComboBox.Items.Add('J')
	[void]$ExtraDrive3_letterComboBox.Items.Add('K')
	[void]$ExtraDrive3_letterComboBox.Items.Add('L')
	[void]$ExtraDrive3_letterComboBox.Items.Add('M')
	[void]$ExtraDrive3_letterComboBox.Items.Add('N')
	[void]$ExtraDrive3_letterComboBox.Items.Add('O')
	[void]$ExtraDrive3_letterComboBox.Items.Add('Q')
	[void]$ExtraDrive3_letterComboBox.Items.Add('R')
	[void]$ExtraDrive3_letterComboBox.Items.Add('S')
	[void]$ExtraDrive3_letterComboBox.Items.Add('T')
	[void]$ExtraDrive3_letterComboBox.Items.Add('U')
	[void]$ExtraDrive3_letterComboBox.Items.Add('V')
	[void]$ExtraDrive3_letterComboBox.Items.Add('W')
	[void]$ExtraDrive3_letterComboBox.Items.Add('X')
	[void]$ExtraDrive3_letterComboBox.Items.Add('Y')
	[void]$ExtraDrive3_letterComboBox.Items.Add('Z')
	$ExtraDrive3_letterComboBox.Location = '6, 170'
	$ExtraDrive3_letterComboBox.Name = 'ExtraDrive3_letterComboBox'
	$ExtraDrive3_letterComboBox.Size = '41, 25'
	$ExtraDrive3_letterComboBox.TabIndex = 34
	#
	# ExtraDrive3_SelectionLabel
	#
	$ExtraDrive3_SelectionLabel.Location = '6, 140'
	$ExtraDrive3_SelectionLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive3_SelectionLabel.Name = 'ExtraDrive3_SelectionLabel'
	$ExtraDrive3_SelectionLabel.Size = '41, 23'
	$ExtraDrive3_SelectionLabel.TabIndex = 33
	$ExtraDrive3_SelectionLabel.Text = 'Drive'
	#
	# ExtraDrive2_letterComboBox
	#
	$ExtraDrive2_letterComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive2_letterComboBox.Enabled = $False
	$ExtraDrive2_letterComboBox.FormattingEnabled = $True
	[void]$ExtraDrive2_letterComboBox.Items.Add('A')
	[void]$ExtraDrive2_letterComboBox.Items.Add('B')
	[void]$ExtraDrive2_letterComboBox.Items.Add('E')
	[void]$ExtraDrive2_letterComboBox.Items.Add('F')
	[void]$ExtraDrive2_letterComboBox.Items.Add('G')
	[void]$ExtraDrive2_letterComboBox.Items.Add('H')
	[void]$ExtraDrive2_letterComboBox.Items.Add('I')
	[void]$ExtraDrive2_letterComboBox.Items.Add('J')
	[void]$ExtraDrive2_letterComboBox.Items.Add('K')
	[void]$ExtraDrive2_letterComboBox.Items.Add('L')
	[void]$ExtraDrive2_letterComboBox.Items.Add('M')
	[void]$ExtraDrive2_letterComboBox.Items.Add('N')
	[void]$ExtraDrive2_letterComboBox.Items.Add('O')
	[void]$ExtraDrive2_letterComboBox.Items.Add('Q')
	[void]$ExtraDrive2_letterComboBox.Items.Add('R')
	[void]$ExtraDrive2_letterComboBox.Items.Add('S')
	[void]$ExtraDrive2_letterComboBox.Items.Add('T')
	[void]$ExtraDrive2_letterComboBox.Items.Add('U')
	[void]$ExtraDrive2_letterComboBox.Items.Add('V')
	[void]$ExtraDrive2_letterComboBox.Items.Add('W')
	[void]$ExtraDrive2_letterComboBox.Items.Add('X')
	[void]$ExtraDrive2_letterComboBox.Items.Add('Y')
	[void]$ExtraDrive2_letterComboBox.Items.Add('Z')
	$ExtraDrive2_letterComboBox.Location = '6, 110'
	$ExtraDrive2_letterComboBox.Name = 'ExtraDrive2_letterComboBox'
	$ExtraDrive2_letterComboBox.Size = '41, 25'
	$ExtraDrive2_letterComboBox.TabIndex = 28
	#
	# ExtraDrive2_SelectionLabel
	#
	$ExtraDrive2_SelectionLabel.Location = '6, 80'
	$ExtraDrive2_SelectionLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive2_SelectionLabel.Name = 'ExtraDrive2_SelectionLabel'
	$ExtraDrive2_SelectionLabel.Size = '41, 23'
	$ExtraDrive2_SelectionLabel.TabIndex = 27
	$ExtraDrive2_SelectionLabel.Text = 'Drive'
	#
	# ExtraDrive1_letterComboBox
	#
	$ExtraDrive1_letterComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive1_letterComboBox.Enabled = $False
	$ExtraDrive1_letterComboBox.FormattingEnabled = $True
	[void]$ExtraDrive1_letterComboBox.Items.Add('A')
	[void]$ExtraDrive1_letterComboBox.Items.Add('B')
	[void]$ExtraDrive1_letterComboBox.Items.Add('E')
	[void]$ExtraDrive1_letterComboBox.Items.Add('F')
	[void]$ExtraDrive1_letterComboBox.Items.Add('G')
	[void]$ExtraDrive1_letterComboBox.Items.Add('H')
	[void]$ExtraDrive1_letterComboBox.Items.Add('I')
	[void]$ExtraDrive1_letterComboBox.Items.Add('J')
	[void]$ExtraDrive1_letterComboBox.Items.Add('K')
	[void]$ExtraDrive1_letterComboBox.Items.Add('L')
	[void]$ExtraDrive1_letterComboBox.Items.Add('M')
	[void]$ExtraDrive1_letterComboBox.Items.Add('N')
	[void]$ExtraDrive1_letterComboBox.Items.Add('O')
	[void]$ExtraDrive1_letterComboBox.Items.Add('Q')
	[void]$ExtraDrive1_letterComboBox.Items.Add('R')
	[void]$ExtraDrive1_letterComboBox.Items.Add('S')
	[void]$ExtraDrive1_letterComboBox.Items.Add('T')
	[void]$ExtraDrive1_letterComboBox.Items.Add('U')
	[void]$ExtraDrive1_letterComboBox.Items.Add('V')
	[void]$ExtraDrive1_letterComboBox.Items.Add('W')
	[void]$ExtraDrive1_letterComboBox.Items.Add('X')
	[void]$ExtraDrive1_letterComboBox.Items.Add('Y')
	[void]$ExtraDrive1_letterComboBox.Items.Add('Z')
	$ExtraDrive1_letterComboBox.Location = '6, 50'
	$ExtraDrive1_letterComboBox.Name = 'ExtraDrive1_letterComboBox'
	$ExtraDrive1_letterComboBox.Size = '41, 25'
	$ExtraDrive1_letterComboBox.TabIndex = 22
	#
	# ExtraDrive1_SelectionLabel
	#
	$ExtraDrive1_SelectionLabel.Location = '5, 20'
	$ExtraDrive1_SelectionLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive1_SelectionLabel.Name = 'ExtraDrive1_SelectionLabel'
	$ExtraDrive1_SelectionLabel.Size = '41, 23'
	$ExtraDrive1_SelectionLabel.TabIndex = 21
	$ExtraDrive1_SelectionLabel.Text = 'Drive'
	#
	# ExtraDrive3_DataStoreComboBox
	#
	$ExtraDrive3_DataStoreComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive3_DataStoreComboBox.Enabled = $False
	$ExtraDrive3_DataStoreComboBox.FormattingEnabled = $True
	$ExtraDrive3_DataStoreComboBox.Location = '171, 170'
	$ExtraDrive3_DataStoreComboBox.Name = 'ExtraDrive3_DataStoreComboBox'
	$ExtraDrive3_DataStoreComboBox.Size = '198, 25'
	$ExtraDrive3_DataStoreComboBox.TabIndex = 38
	#
	# ExtraDrive4_DatastoreLabel
	#
	$ExtraDrive4_DatastoreLabel.Location = '171, 200'
	$ExtraDrive4_DatastoreLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive4_DatastoreLabel.Name = 'ExtraDrive4_DatastoreLabel'
	$ExtraDrive4_DatastoreLabel.Size = '100, 23'
	$ExtraDrive4_DatastoreLabel.TabIndex = 43
	$ExtraDrive4_DatastoreLabel.Text = 'Datastore'
	#
	# ExtraDrive2_DataStoreComboBox
	#
	$ExtraDrive2_DataStoreComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive2_DataStoreComboBox.Enabled = $False
	$ExtraDrive2_DataStoreComboBox.FormattingEnabled = $True
	$ExtraDrive2_DataStoreComboBox.Location = '171, 110'
	$ExtraDrive2_DataStoreComboBox.Name = 'ExtraDrive2_DataStoreComboBox'
	$ExtraDrive2_DataStoreComboBox.Size = '198, 25'
	$ExtraDrive2_DataStoreComboBox.TabIndex = 32
	#
	# ExtraDrive1_DataStoreComboBox
	#
	$ExtraDrive1_DataStoreComboBox.DropDownStyle = 'DropDownList'
	$ExtraDrive1_DataStoreComboBox.Enabled = $False
	$ExtraDrive1_DataStoreComboBox.FormattingEnabled = $True
	$ExtraDrive1_DataStoreComboBox.Location = '171, 50'
	$ExtraDrive1_DataStoreComboBox.Name = 'ExtraDrive1_DataStoreComboBox'
	$ExtraDrive1_DataStoreComboBox.Size = '198, 25'
	$ExtraDrive1_DataStoreComboBox.TabIndex = 26
	#
	# ExtraDrive1_SizeLabel
	#
	$ExtraDrive1_SizeLabel.Location = '65, 20'
	$ExtraDrive1_SizeLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive1_SizeLabel.Name = 'ExtraDrive1_SizeLabel'
	$ExtraDrive1_SizeLabel.Size = '100, 23'
	$ExtraDrive1_SizeLabel.TabIndex = 24
	$ExtraDrive1_SizeLabel.Text = 'Size (GB)'
	#
	# ExtraDrive1_DatastoreLabel
	#
	$ExtraDrive1_DatastoreLabel.Location = '171, 20'
	$ExtraDrive1_DatastoreLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive1_DatastoreLabel.Name = 'ExtraDrive1_DatastoreLabel'
	$ExtraDrive1_DatastoreLabel.Size = '100, 23'
	$ExtraDrive1_DatastoreLabel.TabIndex = 25
	$ExtraDrive1_DatastoreLabel.Text = 'Datastore'
	#
	# ExtraDrive2_SizeLabel
	#
	$ExtraDrive2_SizeLabel.Location = '65, 80'
	$ExtraDrive2_SizeLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive2_SizeLabel.Name = 'ExtraDrive2_SizeLabel'
	$ExtraDrive2_SizeLabel.Size = '100, 23'
	$ExtraDrive2_SizeLabel.TabIndex = 30
	$ExtraDrive2_SizeLabel.Text = 'Size (GB)'
	#
	# ExtraDrive3_SizeLabel
	#
	$ExtraDrive3_SizeLabel.Location = '65, 140'
	$ExtraDrive3_SizeLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive3_SizeLabel.Name = 'ExtraDrive3_SizeLabel'
	$ExtraDrive3_SizeLabel.Size = '100, 23'
	$ExtraDrive3_SizeLabel.TabIndex = 36
	$ExtraDrive3_SizeLabel.Text = 'Size (GB)'
	#
	# ExtraDrive4_SizeLabel
	#
	$ExtraDrive4_SizeLabel.Location = '65, 200'
	$ExtraDrive4_SizeLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive4_SizeLabel.Name = 'ExtraDrive4_SizeLabel'
	$ExtraDrive4_SizeLabel.Size = '100, 23'
	$ExtraDrive4_SizeLabel.TabIndex = 42
	$ExtraDrive4_SizeLabel.Text = 'Size (GB)'
	#
	# ExtraDrive2_DatastoreLabel
	#
	$ExtraDrive2_DatastoreLabel.Location = '171, 80'
	$ExtraDrive2_DatastoreLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive2_DatastoreLabel.Name = 'ExtraDrive2_DatastoreLabel'
	$ExtraDrive2_DatastoreLabel.Size = '100, 23'
	$ExtraDrive2_DatastoreLabel.TabIndex = 31
	$ExtraDrive2_DatastoreLabel.Text = 'Datastore'
	#
	# ExtraDrive3_DatastoreLabel
	#
	$ExtraDrive3_DatastoreLabel.Location = '171, 140'
	$ExtraDrive3_DatastoreLabel.Margin = '3, 3, 3, 3'
	$ExtraDrive3_DatastoreLabel.Name = 'ExtraDrive3_DatastoreLabel'
	$ExtraDrive3_DatastoreLabel.Size = '100, 23'
	$ExtraDrive3_DatastoreLabel.TabIndex = 37
	$ExtraDrive3_DatastoreLabel.Text = 'Datastore'
	#
	# ConfigureVMButton
	#
	$ConfigureVMButton.DialogResult = 'Cancel'
	$ConfigureVMButton.Enabled = $False
	$ConfigureVMButton.Location = '350, 601'
	$ConfigureVMButton.Name = 'ConfigureVMButton'
	$ConfigureVMButton.Size = '105, 50'
	$ConfigureVMButton.TabIndex = 51
	$ConfigureVMButton.Text = 'Configure VM'
	$ConfigureVMButton.UseVisualStyleBackColor = $True
	$ConfigureVMButton.add_Click($ConfigureVMButton_Click)
	#
	# CreateVMButton
	#
	$CreateVMButton.Enabled = $False
	$CreateVMButton.Location = '5, 601'
	$CreateVMButton.Name = 'CreateVMButton'
	$CreateVMButton.Size = '85, 50'
	$CreateVMButton.TabIndex = 14
	$CreateVMButton.Text = 'Create VM'
	$CreateVMButton.UseVisualStyleBackColor = $True
	$CreateVMButton.add_Click($CreateVMButton_Click)
	$groupbox1.ResumeLayout()
	$groupbox2.ResumeLayout()
	$groupbox4.ResumeLayout()
	$groupbox5.ResumeLayout()
	$groupbox6.ResumeLayout()
	$groupbox7.ResumeLayout()
	$groupbox8.ResumeLayout()
	$groupbox9.ResumeLayout()
	$ExtraDriveCounter.EndInit()
	$groupbox10.ResumeLayout()
	$Form.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $Form.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$Form.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$Form.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$Form.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $Form.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	$Global:VMCreationSelections = New-Object –TypeName PSObject
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name VCenterServer -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name Location -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name ResourcePool -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name Name -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name Datastore -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name Template -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name OSCustomizationSpec -Value ''
	$Global:VMCreationSelections | Add-Member -MemberType NoteProperty -Name VCPUs -Value '2'
	
	[Int]$Global:DriveCounter = 0
	[Array]$Global:DriveLetterarray = @('', 'a', 'b', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'q', 'r', 's', 't', 'u', 'v', 'x', 'y', 'z')
	
	
	Function ConnectTo-VCenter{
		
		$Connection = Connect-VIServer -Server $Global:VMCreationSelections.VCenterServer `
									   -Credential $Script:Credentials
		
		If (!$Connection)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to connect to $($Global:VMCreationSelections.VCenterServer) ¯\_(ツ)_/¯."
			return;
		}
		
		Else
		{
			Write-Richtext -LogType 'Success' -LogMsg "Connected to $($Global:VMCreationSelections.VCenterServer)."
			Write-Richtext -LogType 'Informational' -LogMsg "Retrieving Local Offices please be patient."
			Populate-LocalOfficeDropDown
		}
	}
	
	Function Populate-TemplateDropDown{
		$Templates = Get-Template -Server $Global:VMCreationSelections.VCenterServer `
								  -Location $($LocalOfficeSelectionComboBox.SelectedItem)
		
		If (!$Templates)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to Gather templates from $($Global:VMCreationSelections.VCenterServer)."
		}
		
		Else
		{
			Write-Richtext -LogType 'Success' -LogMsg "Templates retrieved from $($Global:VMCreationSelections.VCenterServer)."
			
			$TemplateSelectionComboBox.Items.clear()
			
			Foreach ($Template in $Templates)
			{
				$TemplateSelectionComboBox.Items.Add($Template)
			}
			
			$TemplateSelectionComboBox.enabled = $True
		}
	}
	
	Function Populate-LocalOfficeDropDown{
		
		$LocalOffices = Get-Datacenter -Server $($Global:VMCreationSelections.VCenterServer)
		
		If (!$LocalOffices)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to Gather Local Offices from $($Global:VMCreationSelections.VCenterServer)"
		}
		
		Else
		{
			Write-Richtext -LogType 'Success' -LogMsg "Local Offices retrieved from $($Global:VMCreationSelections.VCenterServer)"
			$LocalOfficeSelectioncomboBox.Items.clear()
			Foreach ($Office in $LocalOffices)
			{
				$LocalOfficeSelectioncomboBox.Items.Add($Office)
			}
			
			$LocalOfficeSelectioncomboBox.enabled = $True
		}
		
	}
	
	Function Populate-CustomizationDropDown{
		
		$Customizations = Get-OSCustomizationSpec -Server $($Global:VMCreationSelections.VCenterServer)
		
		If (!$Customizations)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to Gather customizations from $($Global:VMCreationSelections.VCenterServer)."
		}
		
		Else
		{
			$CustomizationSelectioncomboBox.Items.clear()
			Foreach ($Item in $Customizations)
			{
				$CustomizationSelectioncomboBox.Items.Add($($Item.name))
			}
			
			$CustomizationSelectioncomboBox.enabled = $True
		}
	}
	
	Function Populate-ESXClustersDropDown{
		
		$Clusters = Get-Cluster -Server $($Global:VMCreationSelections.VCenterServer) `
								-location $($LocalOfficeSelectionComboBox.SelectedItem)
		
		$VMHosts = Get-VMHost -Server $($VCenterComboBox.SelectedItem) `
							  -location $($LocalOfficeSelectionComboBox.SelectedItem)
		
		If (!$Clusters -and !$VMHosts)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to Gather ESX Hosts or Clusters."
		}
		
		Else
		{
			Write-Richtext -LogType 'Success' -LogMsg "Clusters retrieved from $($LocalOfficeSelectionComboBox.SelectedItem)."
			$ESXClustersComboBox.Items.clear()
			
			If ($Clusters)
			{
				Foreach ($Item in $Clusters)
				{
					$ESXClustersComboBox.Items.Add($($Item.name))
				}
			}
			If ($VMHosts)
			{
				Foreach ($Item in $VMHosts)
				{
					$ESXClustersComboBox.Items.Add($($Item.name))
				}
			}
			$ESXClustersComboBox.enabled = $True
		}
		
	}
	
	Function Populate-DatastoreClusterDropDown{
		
		$DataStoreClusters = Get-Cluster -Server $Global:VMCreationSelections.VCenterServer `
										 -Name $($ESXClustersComboBox.SelectedItem) `
		| Get-Datastore | Get-DatastoreCluster
		
		$DataStores = Get-VMHOST -Server $Global:VMCreationSelections.VCenterServer `
								 -Name $ESXClustersComboBox.SelectedItem `
		| Get-Datastore
		
		If (!$DataStoreClusters -and !$DataStores)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to pull and DataStore Clusters or Datastores from  $($ESXClustersComboBox.SelectedItem). "
		}
		
		Else
		{
			Write-Richtext -LogType 'Success' -LogMsg "DataStores or Clusters retrieved from $($ESXClustersComboBox.SelectedItem)."
			$DataStoreClusterComboBox.Items.clear()
			
			If ($DataStoreClusters)
			{
				Foreach ($Item in $DataStoreClusters)
				{
					$DataStoreClusterComboBox.Items.Add($Item.name)
				}
			}
			
			If ($DataStores)
			{
				Foreach ($Item in $DataStores)
				{
					$DataStoreClusterComboBox.Items.Add($Item.name)
				}
			}
			$DataStoreClusterComboBox.enabled = $True
		}
		
	}
	
	Function Populate-ExtraDiskClusterDropDown{
		param
		(
			[System.Windows.Forms.ComboBox]$ComboBox
		)
		
		$DataStoreClusters = Get-Cluster -Server $Global:VMCreationSelections.VCenterServer `
										 -Name $($ESXClustersComboBox.SelectedItem) `
		| Get-Datastore | Get-DatastoreCluster
		
		$DataStores = Get-VMHOST -Server $Global:VMCreationSelections.VCenterServer `
								 -Name $ESXClustersComboBox.SelectedItem `
		| Get-Datastore
		
		If (!$DataStoreClusters -and !$DataStores)
		{
			Write-Richtext -LogType 'Error' -LogMsg "Unable to pull and DataStore Clusters or Datastores from  $($ESXClustersComboBox.SelectedItem). "
		}
		
		Else
		{
			Write-Richtext -LogType 'Success' -LogMsg "DataStores or Clusters retrieved from $($ESXClustersComboBox.SelectedItem)."
			$DataStoreClusterComboBox.Items.clear()
			
			If ($DataStoreClusters)
			{
				Foreach ($Item in $DataStoreClusters)
				{
					$ComboBox.Items.Add($Item.name)
				}
			}
			
			If ($DataStores)
			{
				Foreach ($Item in $DataStores)
				{
					$ComboBox.Items.Add($Item.name)
				}
			}
		}
		
	}
	
	Function Set-VMCPUCount{
		$VM = Get-VM -Server $Global:VMCreationSelections.VCenterServer `
					 -Location $Global:VMCreationSelections.Location `
					 -Name $Global:VMCreationSelections.Name
		
		$Set = Set-VM -Server $Global:VMCreationSelections.VCenterServer `
					  -VM $VM `
					  -NumCpu $VCPUsComboBox.SelectedItem `
					  -Confirm
		
		If ($Set.numcpu -eq $VCPUsComboBox.SelectedItem)
		{
			Write-RichText -LogType success -LogMsg "VCPU Count Set to $($Set.numcpu)"
			
		}
		
		Else
		{
			Write-RichText -LogType Error -LogMsg "Unable to Set VCPU Count!!"
		}
	}
	
	Function Set-VMRamAmount{
		$VM = Get-VM -Server $Global:VMCreationSelections.VCenterServer `
					 -Location $Global:VMCreationSelections.Location `
					 -Name $Global:VMCreationSelections.Name
		
		$Set = Set-VM -Server $Global:VMCreationSelections.VCenterServer `
					  -VM $VM `
					  -MemoryGB $RamComboBox.SelectedItem `
					  -Confirm
		
		If ($Set.MemoryGB -eq $RamComboBox.SelectedItem)
		{
			Write-RichText -LogType success -LogMsg "RAM Amount (GB) Set to $($Set.numcpu)"
			
		}
		
		Else
		{
			Write-RichText -LogType Error -LogMsg "Unable to Set RAM Value!!"
		}
	}
	
	Function Add-VMDIsks{
		$VM = Get-VM -Server $Global:VMCreationSelections.VCenterServer `
					 -Location $Global:VMCreationSelections.Location `
					 -Name $Global:VMCreationSelections.Name
		
		If ($ExtraDrive1_LetterComboBox.enabled -eq $true){
			If ($ExtraDrive1_LetterComboBox.SelectedIndex -ne 0 `
			-and $ExtraDrive1_SizeTextBox.text -ne '' `
			-and $ExtraDrive1_DataStoreComboBox.selectedindex -ne 0){
				
				New-HardDisk -VM $VM `
							 -CapacityGB $ExtraDrive1_SizeTextBox.text `
							 -DataStore $ExtraDrive1_DataStoreComboBox.selectedindex `
							 -Confirm $False `
							 -DiskPath $Path `
							 -Server $Global:VMCreationSelections.VCenterServer `
							 -StorageFormat Thin
			}
		}
		If ($ExtraDrive2_LetterComboBox.enabled -eq $true){
			If ($ExtraDrive2_LetterComboBox.SelectedIndex -ne 0 `
			-and $ExtraDrive2_SizeTextBox.text -ne '' `
			-and $ExtraDrive2_DataStoreComboBox.selectedindex -ne 0)
			{
				
				New-HardDisk -VM $VM `
							 -CapacityGB $ExtraDrive2_SizeTextBox.text `
							 -DataStore $ExtraDrive2_DataStoreComboBox.selectedindex `
							 -Confirm $False `
							 -DiskPath $Path `
							 -Server $Global:VMCreationSelections.VCenterServer `
							 -StorageFormat Thin
			}
		}
		If ($ExtraDrive3_LetterComboBox.enabled -eq $true){
			If ($ExtraDrive3_LetterComboBox.SelectedIndex -ne 0 `
			-and $ExtraDrive3_SizeTextBox.text -ne '' `
			-and $ExtraDrive3_DataStoreComboBox.selectedindex -ne 0)
			{
				
				New-HardDisk -VM $VM `
							 -CapacityGB $ExtraDrive3_SizeTextBox.text `
							 -DataStore $ExtraDrive3_DataStoreComboBox.selectedindex `
							 -Confirm $False `
							 -DiskPath $Path `
							 -Server $Global:VMCreationSelections.VCenterServer `
							 -StorageFormat Thin
			}
		}
		If ($ExtraDrive4_LetterComboBox.enabled -eq $true){
			If ($ExtraDrive4_LetterComboBox.SelectedIndex -ne 0 `
			-and $ExtraDrive4_SizeTextBox.text -ne '' `
			-and $ExtraDrive4_DataStoreComboBox.selectedindex -ne 0)
			{
				
				New-HardDisk -VM $VM `
							 -CapacityGB $ExtraDrive4_SizeTextBox.text `
							 -DataStore $ExtraDrive4_DataStoreComboBox.selectedindex `
							 -Confirm $False `
							 -DiskPath $Path `
							 -Server $Global:VMCreationSelections.VCenterServer `
							 -StorageFormat Thin
			}
		}
		If ($ExtraDrive5_LetterComboBox.enabled -eq $true){
			If ($ExtraDrive5_LetterComboBox.SelectedIndex -ne 0 `
			-and $ExtraDrive5_SizeTextBox.text -ne '' `
			-and $ExtraDrive5_DataStoreComboBox.selectedindex -ne 0)
			{
				
				New-HardDisk -VM $VM `
							 -CapacityGB $ExtraDrive5_SizeTextBox.text `
							 -DataStore $ExtraDrive5_DataStoreComboBox.selectedindex `
							 -Confirm $False `
							 -DiskPath $Path `
							 -Server $Global:VMCreationSelections.VCenterServer `
							 -StorageFormat Thin
			}
		}
		
	}
	
	function Control-VisibleExtraDrives{
		
		switch ($Global:DriveCounter)
		{
			0 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $false
				$ExtraDrive1_letterComboBox.enabled = $false
				$ExtraDrive1_SelectionLabel.enabled = $false
				$ExtraDrive1SizeTextBox.enabled = $false
				$ExtraDrive1_SizeLabel.enabled = $false
				$ExtraDrive1_DatastoreLabel.enabled = $false
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $false
				$ExtraDrive2_letterComboBox.enabled = $false
				$ExtraDrive2_SelectionLabel.enabled = $false
				$ExtraDrive2SizeTextBox.enabled = $false
				$ExtraDrive2_SizeLabel.enabled = $false
				$ExtraDrive2_DatastoreLabel.enabled = $false
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $false
				$ExtraDrive3_letterComboBox.enabled = $false
				$ExtraDrive3_SelectionLabel.enabled = $false
				$ExtraDrive3SizeTextBox.enabled = $false
				$ExtraDrive3_SizeLabel.enabled = $false
				$ExtraDrive3_DatastoreLabel.enabled = $false
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SelectionLabel.enabled = $false
				$ExtraDrive4SizeTextBox.enabled = $false
				$ExtraDrive4_SizeLabel.enabled = $false
				$ExtraDrive4_DatastoreLabel.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SelectionLabel.enabled = $false
				$ExtraDrive5SizeTextBox.enabled = $false
				$ExtraDrive5_SizeLabel.enabled = $false
				$ExtraDrive5_DatastoreLabel.enabled = $false
				
			}
			1 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SelectionLabel.enabled = $true
				$ExtraDrive1SizeTextBox.enabled = $true
				$ExtraDrive1_SizeLabel.enabled = $true
				$ExtraDrive1_DatastoreLabel.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $false
				$ExtraDrive2_letterComboBox.enabled = $false
				$ExtraDrive2_SelectionLabel.enabled = $false
				$ExtraDrive2SizeTextBox.enabled = $false
				$ExtraDrive2_SizeLabel.enabled = $false
				$ExtraDrive2_DatastoreLabel.enabled = $false
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $false
				$ExtraDrive3_letterComboBox.enabled = $false
				$ExtraDrive3_SelectionLabel.enabled = $false
				$ExtraDrive3SizeTextBox.enabled = $false
				$ExtraDrive3_SizeLabel.enabled = $false
				$ExtraDrive3_DatastoreLabel.enabled = $false
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SelectionLabel.enabled = $false
				$ExtraDrive4SizeTextBox.enabled = $false
				$ExtraDrive4_SizeLabel.enabled = $false
				$ExtraDrive4_DatastoreLabel.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SelectionLabel.enabled = $false
				$ExtraDrive5SizeTextBox.enabled = $false
				$ExtraDrive5_SizeLabel.enabled = $false
				$ExtraDrive5_DatastoreLabel.enabled = $false
			}
			2 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SelectionLabel.enabled = $true
				$ExtraDrive1SizeTextBox.enabled = $true
				$ExtraDrive1_SizeLabel.enabled = $true
				$ExtraDrive1_DatastoreLabel.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SelectionLabel.enabled = $true
				$ExtraDrive2SizeTextBox.enabled = $true
				$ExtraDrive2_SizeLabel.enabled = $true
				$ExtraDrive2_DatastoreLabel.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $false
				$ExtraDrive3_letterComboBox.enabled = $false
				$ExtraDrive3_SelectionLabel.enabled = $false
				$ExtraDrive3SizeTextBox.enabled = $false
				$ExtraDrive3_SizeLabel.enabled = $false
				$ExtraDrive3_DatastoreLabel.enabled = $false
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SelectionLabel.enabled = $false
				$ExtraDrive4SizeTextBox.enabled = $false
				$ExtraDrive4_SizeLabel.enabled = $false
				$ExtraDrive4_DatastoreLabel.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SelectionLabel.enabled = $false
				$ExtraDrive5SizeTextBox.enabled = $false
				$ExtraDrive5_SizeLabel.enabled = $false
				$ExtraDrive5_DatastoreLabel.enabled = $false
			}
			3 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SelectionLabel.enabled = $true
				$ExtraDrive1SizeTextBox.enabled = $true
				$ExtraDrive1_SizeLabel.enabled = $true
				$ExtraDrive1_DatastoreLabel.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SelectionLabel.enabled = $true
				$ExtraDrive2SizeTextBox.enabled = $true
				$ExtraDrive2_SizeLabel.enabled = $true
				$ExtraDrive2_DatastoreLabel.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $true
				$ExtraDrive3_letterComboBox.enabled = $true
				$ExtraDrive3_SelectionLabel.enabled = $true
				$ExtraDrive3SizeTextBox.enabled = $true
				$ExtraDrive3_SizeLabel.enabled = $true
				$ExtraDrive3_DatastoreLabel.enabled = $true
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $false
				$ExtraDrive4_letterComboBox.enabled = $false
				$ExtraDrive4_SelectionLabel.enabled = $false
				$ExtraDrive4SizeTextBox.enabled = $false
				$ExtraDrive4_SizeLabel.enabled = $false
				$ExtraDrive4_DatastoreLabel.enabled = $false
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SelectionLabel.enabled = $false
				$ExtraDrive5SizeTextBox.enabled = $false
				$ExtraDrive5_SizeLabel.enabled = $false
				$ExtraDrive5_DatastoreLabel.enabled = $false
			}
			4 {
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SelectionLabel.enabled = $true
				$ExtraDrive1SizeTextBox.enabled = $true
				$ExtraDrive1_SizeLabel.enabled = $true
				$ExtraDrive1_DatastoreLabel.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SelectionLabel.enabled = $true
				$ExtraDrive2SizeTextBox.enabled = $true
				$ExtraDrive2_SizeLabel.enabled = $true
				$ExtraDrive2_DatastoreLabel.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $true
				$ExtraDrive3_letterComboBox.enabled = $true
				$ExtraDrive3_SelectionLabel.enabled = $true
				$ExtraDrive3SizeTextBox.enabled = $true
				$ExtraDrive3_SizeLabel.enabled = $true
				$ExtraDrive3_DatastoreLabel.enabled = $true
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $true
				$ExtraDrive4_letterComboBox.enabled = $true
				$ExtraDrive4_SelectionLabel.enabled = $true
				$ExtraDrive4SizeTextBox.enabled = $true
				$ExtraDrive4_SizeLabel.enabled = $true
				$ExtraDrive4_DatastoreLabel.enabled = $true
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $false
				$ExtraDrive5_letterComboBox.enabled = $false
				$ExtraDrive5_SelectionLabel.enabled = $false
				$ExtraDrive5SizeTextBox.enabled = $false
				$ExtraDrive5_SizeLabel.enabled = $false
				$ExtraDrive5_DatastoreLabel.enabled = $false
			}
			5{
				#ED1
				$ExtraDrive1_DataStoreComboBox.enabled = $true
				$ExtraDrive1_letterComboBox.enabled = $true
				$ExtraDrive1_SelectionLabel.enabled = $true
				$ExtraDrive1SizeTextBox.enabled = $true
				$ExtraDrive1_SizeLabel.enabled = $true
				$ExtraDrive1_DatastoreLabel.enabled = $true
				#ED2
				$ExtraDrive2_DataStoreComboBox.enabled = $true
				$ExtraDrive2_letterComboBox.enabled = $true
				$ExtraDrive2_SelectionLabel.enabled = $true
				$ExtraDrive2SizeTextBox.enabled = $true
				$ExtraDrive2_SizeLabel.enabled = $true
				$ExtraDrive2_DatastoreLabel.enabled = $true
				#ED3
				$ExtraDrive3_DataStoreComboBox.enabled = $true
				$ExtraDrive3_letterComboBox.enabled = $true
				$ExtraDrive3_SelectionLabel.enabled = $true
				$ExtraDrive3SizeTextBox.enabled = $true
				$ExtraDrive3_SizeLabel.enabled = $true
				$ExtraDrive3_DatastoreLabel.enabled = $true
				#ED4
				$ExtraDrive4_DataStoreComboBox.enabled = $true
				$ExtraDrive4_letterComboBox.enabled = $true
				$ExtraDrive4_SelectionLabel.enabled = $true
				$ExtraDrive4SizeTextBox.enabled = $true
				$ExtraDrive4_SizeLabel.enabled = $true
				$ExtraDrive4_DatastoreLabel.enabled = $true
				#ED5
				$ExtraDrive5_DataStoreComboBox.enabled = $true
				$ExtraDrive5_letterComboBox.enabled = $true
				$ExtraDrive5_SelectionLabel.enabled = $true
				$ExtraDrive5SizeTextBox.enabled = $true
				$ExtraDrive5_SizeLabel.enabled = $true
				$ExtraDrive5_DatastoreLabel.enabled = $true
			}
		}
	}
	
	Function Write-RichText{
		<#
		.SYNOPSIS
			A function to output text to a Rich Text Box.
		
		.DESCRIPTION
			This function appends text to a Rich Text Box and colors it based 
	        upon the type of message being displayed.
	
	    .PARAM Logtype
	        Used to determine if the text is a success or error message or purely
	        informational.
	
	    .PARAM LogMSG
	        The message to be added to the RichTextBox.
		
		.EXAMPLE
			Write-Richtext -LogType Error -LogMsg "This is an Error."
			Write-Richtext -LogType Success -LogMsg "This is a Success."
			Write-Richtext -LogType Informational -LogMsg "This is Informational."
		
		.NOTES
			N/A
	#>
		
		Param
		(
			[Parameter(Mandatory = $true, Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName)]
			[String]$LogType,
			[Parameter(Mandatory = $true, Position = 1, ValueFromPipeline, ValueFromPipelineByPropertyName)]
			[String]$LogMsg
		)
		
		switch ($logtype)
		{
			Error {
				$richtextbox1.SelectionColor = 'Red'
				$richtextbox1.AppendText("`n $logmsg")
				
			}
			Success {
				$richtextbox1.SelectionColor = 'Green'
				$richtextbox1.AppendText("`n $logmsg")
				
			}
			Informational {
				$richtextbox1.SelectionColor = 'Blue'
				$richtextbox1.AppendText("`n $logmsg")
				
			}
			
		}
		
	}
	
	function Load-ExtraDriveComboBoxes{
		
		Load-ComboBox -ComboBox -$ExtraDrive1_letterComboBox `
					  -Items $Global:DriveLetterarray
		
		Load-ComboBox -ComboBox -$ExtraDrive2_letterComboBox `
					  -Items $Global:DriveLetterarray
		
		Load-ComboBox -ComboBox -$ExtraDrive3_letterComboBox `
					  -Items $Global:DriveLetterarray
		
		Load-ComboBox -ComboBox -$ExtraDrive4_letterComboBox `
					  -Items $Global:DriveLetterarray
		
		Load-ComboBox -ComboBox -$ExtraDrive5_letterComboBox `
					  -Items $Global:DriveLetterarray
		
	}
	
	#endregion Source: Globals.ps1

#Start the application
Main ($CommandLine)
